version: '3.8'
services:
  app:
    build: .
    ports: ["8080:8080"]
    depends_on: [db]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskmaster_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: taskmaster_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports: ["5432:5432"]
